In [2]:
import torch

In [14]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x+2
print(y)
z = y*y*2
z = z.mean()
print(z)

tensor([-1.1522,  0.8540,  0.9824], requires_grad=True)
tensor([0.8478, 2.8540, 2.9824], grad_fn=<AddBackward0>)
tensor(11.8391, grad_fn=<MeanBackward0>)


In [15]:
z.backward() # dz / dx
print(x.grad)

tensor([1.1304, 3.8053, 3.9766])


In [16]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x+2
print(y)
z = y*y*2
#z = z.mean()
print(z)
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([ 0.7024,  0.9008, -0.6180], requires_grad=True)
tensor([2.7024, 2.9008, 1.3820], grad_fn=<AddBackward0>)
tensor([14.6064, 16.8288,  3.8196], grad_fn=<MulBackward0>)
tensor([1.0810e+00, 1.1603e+01, 5.5278e-03])


In [20]:
x = torch.randn(3, requires_grad=True)
print(x)

# x.requires_grad_(False)
x.requires_grad_(False)
print(x)

tensor([ 0.1421, -1.0988, -0.4089], requires_grad=True)
tensor([ 0.1421, -1.0988, -0.4089])


In [21]:
x = torch.randn(3, requires_grad=True)
print(x)

# x.detach()
y = x.detach()
print(y)

tensor([-0.5775,  1.2021,  1.1024], requires_grad=True)
tensor([-0.5775,  1.2021,  1.1024])


In [22]:
x = torch.randn(3, requires_grad=True)
print(x)

# with torch.no_grad():
with torch.no_grad():
    y = x + 2
    print(y)

tensor([0.4507, 0.5157, 0.1474], requires_grad=True)
tensor([2.4507, 2.5157, 2.1474])


In [23]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x + 2
print(y)

tensor([ 0.6809,  1.5758, -0.0190], requires_grad=True)
tensor([2.6809, 3.5758, 1.9810], grad_fn=<AddBackward0>)


In [27]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    # weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [28]:
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()


TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor