In [33]:
import torch
import numpy as np


In [6]:
x = torch.empty(2, 4)
print(x)

tensor([[ 0.0000e+00,  4.4766e+00,  2.3694e-38,  2.3694e-38],
        [ 0.0000e+00,  2.0000e+00,  6.7854e-29, -1.5846e+29]])


In [15]:
x = torch.ones(3, 3, dtype=torch.float16)
print(x)
print(x.size())
print(x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)
torch.Size([3, 3])
torch.float16


In [21]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y
print(z)
z = torch.add(x, y)
print(z)
y.add_(x)
print(y)

z = x*y 
print(z)
z = torch.mul(x, y)
print(z)

tensor([[0.2363, 0.9350],
        [0.0947, 0.3268]])
tensor([[0.6679, 0.9769],
        [0.9924, 0.3308]])
tensor([[0.9043, 1.9120],
        [1.0871, 0.6576]])
tensor([[0.9043, 1.9120],
        [1.0871, 0.6576]])
tensor([[0.9043, 1.9120],
        [1.0871, 0.6576]])
tensor([[0.2137, 1.7877],
        [0.1030, 0.2149]])
tensor([[0.2137, 1.7877],
        [0.1030, 0.2149]])


In [27]:
x = torch.rand(5, 3)
print(x)
print(x[:, 0])
print(x[1, :])
print(x[1, 1].item())


tensor([[0.5397, 0.4650, 0.7974],
        [0.4707, 0.2157, 0.7947],
        [0.2965, 0.8673, 0.8191],
        [0.8366, 0.1379, 0.1382],
        [0.9308, 0.0367, 0.4583]])
tensor([0.5397, 0.4707, 0.2965, 0.8366, 0.9308])
tensor([0.4707, 0.2157, 0.7947])
0.21565133333206177


In [32]:
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)
y = x.view(-1, 8)
print(y.size())

tensor([[0.5911, 0.2465, 0.5216, 0.9873],
        [0.1152, 0.4763, 0.6796, 0.5204],
        [0.6469, 0.2015, 0.6824, 0.0137],
        [0.4019, 0.3848, 0.4236, 0.3290]])
tensor([0.5911, 0.2465, 0.5216, 0.9873, 0.1152, 0.4763, 0.6796, 0.5204, 0.6469,
        0.2015, 0.6824, 0.0137, 0.4019, 0.3848, 0.4236, 0.3290])
torch.Size([2, 8])


In [38]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
print(type(b))

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [41]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [43]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
#    z.numpy() # numpy only cpu
    z = z.to("cpu")

In [44]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
